BOOTLOADER = caterina

MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
UNICODE_ENABLE = no

# TODO: TEST that this does not cause issues
#EXTRAKEY_ENABLE = no
#NKRO_ENABLE = no

